### ISSUE TITLE
Channel schließen, falls Raum gelöscht wird

### ISSUE THREAD

**Issue by mariusfriess** [KIT-PSE/collab-space-app#30]
Falls ein Lehrer einen Raum in seiner Übersicht löscht, wird der dazugehörige Channel (falls aktiv) nicht beendet/gelöscht. Der Channel sollte dann aber natürlich auch geschlossen werden und alle Schüler die sich noch darin befinden rausgeworfen.

**Comment by mariusfriess** [comment]
Ist nicht behoben?

**Comment by FlorianRaith** [comment]
Whoops, hab den falschen issue referenziert
